export const predefinedStyles = {
  slider: [
    {
      widgetName: "Slider 1",
      widgetType: "slider-1",
      ratingFilter: "all",
      footerText: "show",
      verifiedIcon: "show",
      platformLogos: "show",
      platformStars: "show",
      reviewSources: "all",
      colorSchema: "light-background",
      navigationArrows: "show",
      navigationDots: "show",
      textAlign: "left",
      nameColor: "#000009",
      nameSize: 18,
      reviewColor: "#475569",
      reviewSize: 14,
      backgroundColor: "#efefef",
      borderColor: "#efefef",
      borderWeight: 0,
      padding: 16,
      borderRadius: 4,
      dropShadow: "hide",
      backgroundOpacity: 1,
      mouseAnimation: "yes",
      outerBackgroundColor: "#fdffff",
      outerTextColor: "#000009",
    },
    {
      widgetName: "Slider 1 Centered",
      widgetType: "slider-1-centered",
      ratingFilter: "all",
      footerText: "hide",
      verifiedIcon: "show",
      platformLogos: "show",
      platformStars: "show",
      reviewSources: "all",
      colorSchema: "light-background",
      navigationArrows: "show",
      navigationDots: "hide",
      textAlign: "center",
      nameColor: "#000009",
      nameSize: 18,
      reviewColor: "#475569",
      reviewSize: 14,
      backgroundColor: "#efefef",
      borderColor: "#efefef",
      borderWeight: 0,
      padding: 16,
      borderRadius: 4,
      dropShadow: "hide",
      backgroundOpacity: 1,
      mouseAnimation: "yes",
      outerBackgroundColor: "#fdffff",
      outerTextColor: "#000009",
    },
  ],
  badge: [
    {
      widgetName: "Badge 1 Html",
      widgetType: "badge-1-html",
      ratingFilter: "all",
      footerText: "hide",
      verifiedIcon: "show",
      platformLogos: "show",
      platformStars: "show",
      reviewSources: "all",
      colorSchema: "light-background",
      navigationArrows: "show",
      navigationDots: "hide",
      textAlign: "center",
      nameColor: "#000009",
      nameSize: 20,
      reviewColor: "#000009",
      reviewSize: 20,
      backgroundColor: "#efefef",
      borderColor: "#efefef",
      borderWeight: 0,
      padding: 24,
      borderRadius: 4,
      dropShadow: "hide",
      backgroundOpacity: 1,
      mouseAnimation: "yes",
      outerBackgroundColor: "#fdffff",
      outerTextColor: "#000009",
    },
  ],
  grid: [
    {
      widgetName: "Grid 1",
      widgetType: "grid-1",
      ratingFilter: "all",
      footerText: "show",
      verifiedIcon: "show",
      platformLogos: "show",
      platformStars: "show",
      reviewSources: "all",
      colorSchema: "light-background",
      navigationArrows: "show",
      navigationDots: "show",
      textAlign: "left",
      nameColor: "#000009",
      nameSize: 18,
      reviewColor: "#475569",
      reviewSize: 14,
      backgroundColor: "#efefef",
      borderColor: "#efefef",
      borderWeight: 0,
      padding: 16,
      borderRadius: 4,
      dropShadow: "hide",
      backgroundOpacity: 1,
      mouseAnimation: "yes",
      outerBackgroundColor: "#fdffff",
      outerTextColor: "#000009",
    },
    {
      widgetName: "Grid 1 Centered",
      widgetType: "grid-1-centered",
      ratingFilter: "all",
      footerText: "hide",
      verifiedIcon: "show",
      platformLogos: "show",
      platformStars: "show",
      reviewSources: "all",
      colorSchema: "light-background",
      navigationArrows: "show",
      navigationDots: "hide",
      textAlign: "center",
      nameColor: "#000009",
      nameSize: 18,
      reviewColor: "#475569",
      reviewSize: 14,
      backgroundColor: "#efefef",
      borderColor: "#efefef",
      borderWeight: 0,
      padding: 16,
      borderRadius: 4,
      dropShadow: "hide",
      backgroundOpacity: 1,
      mouseAnimation: "yes",
      outerBackgroundColor: "#fdffff",
      outerTextColor: "#000009",
    },
  ],
  list: [
    {
      widgetName: "List 1",
      widgetType: "list-1",
      ratingFilter: "all",
      footerText: "show",
      verifiedIcon: "show",
      platformLogos: "show",
      platformStars: "show",
      reviewSources: "all",
      colorSchema: "light-background",
      navigationArrows: "show",
      navigationDots: "show",
      textAlign: "left",
      nameColor: "#000009",
      nameSize: 18,
      reviewColor: "#475569",
      reviewSize: 14,
      backgroundColor: "#efefef",
      borderColor: "#efefef",
      borderWeight: 0,
      padding: 16,
      borderRadius: 4,
      dropShadow: "hide",
      backgroundOpacity: 1,
      mouseAnimation: "yes",
      outerBackgroundColor: "#fdffff",
      outerTextColor: "#000009",
    },
    {
      widgetName: "List 1 Centered",
      widgetType: "list-1-centered",
      ratingFilter: "all",
      footerText: "hide",
      verifiedIcon: "show",
      platformLogos: "show",
      platformStars: "show",
      reviewSources: "all",
      colorSchema: "light-background",
      navigationArrows: "show",
      navigationDots: "hide",
      textAlign: "center",
      nameColor: "#000009",
      nameSize: 18,
      reviewColor: "#475569",
      reviewSize: 14,
      backgroundColor: "#efefef",
      borderColor: "#efefef",
      borderWeight: 0,
      padding: 16,
      borderRadius: 4,
      dropShadow: "hide",
      backgroundOpacity: 1,
      mouseAnimation: "yes",
      outerBackgroundColor: "#fdffff",
      outerTextColor: "#000009",
    },
  ],
  button: [
    {
      widgetName: "Button 1",
      widgetType: "button-1",
      ratingFilter: "all",
      footerText: "hide",
      verifiedIcon: "show",
      platformLogos: "show",
      platformStars: "show",
      reviewSources: "all",
      colorSchema: "light-background",
      navigationArrows: "show",
      navigationDots: "hide",
      textAlign: "center",
      nameColor: "#000009",
      nameSize: 14,
      reviewColor: "#000009",
      reviewSize: 14,
      backgroundColor: "#efefef",
      borderColor: "#efefef",
      borderWeight: 0,
      padding: 24,
      borderRadius: 4,
      dropShadow: "hide",
      backgroundOpacity: 1,
      mouseAnimation: "yes",
      outerBackgroundColor: "#fdffff",
      outerTextColor: "#000009",
    },
    {
      widgetName: "Button 2",
      widgetType: "button-2",
      ratingFilter: "all",
      footerText: "hide",
      verifiedIcon: "show",
      platformLogos: "show",
      platformStars: "show",
      reviewSources: "all",
      colorSchema: "light-background",
      navigationArrows: "show",
      navigationDots: "hide",
      textAlign: "center",
      nameColor: "#000009",
      nameSize: 14,
      reviewColor: "#000009",
      reviewSize: 14,
      backgroundColor: "#efefef",
      borderColor: "#efefef",
      borderWeight: 0,
      padding: 24,
      borderRadius: 4,
      dropShadow: "hide",
      backgroundOpacity: 1,
      mouseAnimation: "yes",
      outerBackgroundColor: "#fdffff",
      outerTextColor: "#000009",
    },
    {
      widgetName: "Button 3",
      widgetType: "button-3",
      ratingFilter: "all",
      footerText: "hide",
      verifiedIcon: "show",
      platformLogos: "show",
      platformStars: "show",
      reviewSources: "all",
      colorSchema: "light-background",
      navigationArrows: "show",
      navigationDots: "hide",
      textAlign: "center",
      nameColor: "#000009",
      nameSize: 14,
      reviewColor: "#000009",
      reviewSize: 14,
      backgroundColor: "#efefef",
      borderColor: "#efefef",
      borderWeight: 0,
      padding: 24,
      borderRadius: 4,
      dropShadow: "hide",
      backgroundOpacity: 1,
      mouseAnimation: "yes",
      outerBackgroundColor: "#fdffff",
      outerTextColor: "#000009",
    },
    {
      widgetName: "Button 4",
      widgetType: "button-4",
      ratingFilter: "all",
      footerText: "hide",
      verifiedIcon: "show",
      platformLogos: "show",
      platformStars: "show",
      reviewSources: "all",
      colorSchema: "light-background",
      navigationArrows: "show",
      navigationDots: "hide",
      textAlign: "center",
      nameColor: "#000009",
      nameSize: 14,
      reviewColor: "#000009",
      reviewSize: 14,
      backgroundColor: "#efefef",
      borderColor: "#efefef",
      borderWeight: 0,
      padding: 24,
      borderRadius: 4,
      dropShadow: "hide",
      backgroundOpacity: 1,
      mouseAnimation: "yes",
      outerBackgroundColor: "#fdffff",
      outerTextColor: "#000009",
    },
  ],
};
